Number of multiplications will be "n x m x k"
Number of additions will be "n x m x (k-1)"


In [11]:

import random
import time
import numpy as np

rows_A = 3
cols_A = 4
cols_B = 2

def create_matrix(num_rows, num_cols):
    return [random.sample(range(1, 10), num_cols) for _ in range(num_rows)]

matrix_A = create_matrix(rows_A, cols_A)
matrix_B = create_matrix(cols_A, cols_B)

print("Matrix A:")
print(matrix_A)
print("Matrix B:")
print(matrix_B)

def matrix_multiply(matrix_A, matrix_B):
    num_rows_A = len(matrix_A)
    num_cols_A = len(matrix_A[0])
    num_rows_B = len(matrix_B)
    num_cols_B = len(matrix_B[0])

    if num_cols_A != num_rows_B:
        return -1
    
    result_matrix = [[0 for _ in range(num_cols_B)] for _ in range(num_rows_A)]
    
    for i in range(num_rows_A):
        for j in range(num_cols_B):
            for k in range(num_cols_A):
                result_matrix[i][j] += matrix_A[i][k] * matrix_B[k][j]

    return result_matrix

start_time = time.time()
result_matrix = matrix_multiply(matrix_A, matrix_B)
end_time = time.time()

print("Resultant Matrix:")
print(result_matrix)
time_python = end_time - start_time
print(f"Elapsed Time: {time_python:.6f} seconds")

mat_A_np = np.array(matrix_A)
mat_B_np = np.array(matrix_B)
print("Matrix A (NumPy):")
print(mat_A_np)
print("Matrix B (NumPy):")
print(mat_B_np)

start_time = time.time()
res_Mat_np = np.dot(mat_A_np, mat_B_np)
end_time = time.time()

print("Resultant Matrix from NumPy:")
print(res_Mat_np)
time_numpy = end_time - start_time
print(f"Elapsed Time for NumPy: {time_numpy:.6f} seconds")

time_difference = time_numpy - time_python
print(f"Time Difference: {time_difference:.6f} seconds")


Matrix A:
[[5, 7, 8, 3], [2, 4, 5, 9], [5, 1, 3, 8]]
Matrix B:
[[4, 6], [4, 9], [5, 9], [4, 2]]
Resultant Matrix:
[[100, 171], [85, 111], [71, 82]]
Elapsed Time: 0.000000 seconds
Matrix A (NumPy):
[[5 7 8 3]
 [2 4 5 9]
 [5 1 3 8]]
Matrix B (NumPy):
[[4 6]
 [4 9]
 [5 9]
 [4 2]]
Resultant Matrix from NumPy:
[[100 171]
 [ 85 111]
 [ 71  82]]
Elapsed Time for NumPy: 0.000000 seconds
Time Difference: 0.000000 seconds


In [12]:
import jax
import jax.numpy as jnp

def f(x, y):
    return 3 * x**2 * y + 4 * y**3

grad_f = jax.grad(f, argnums=(0, 1))

x, y = 1.0, 2.0

grad_analytical = (6 * x * y, 3 * x**2 + 12 * y**2)
grad_jax = grad_f(x, y)

print(f"Analytical Gradient: {grad_analytical}")
print(f"JAX Gradient: {grad_jax}")


Analytical Gradient: (12.0, 51.0)
JAX Gradient: (Array(12., dtype=float32, weak_type=True), Array(51., dtype=float32, weak_type=True))


Q4. What is the gradient of the following function with respect to x and y? x^2y + y^3sin(x)

(x^2)*y + (y^3)sin(x)

gradient with respect to x 2xy + (y^3)cos(x)

gradient with respect to y x^2 + 3*(y^2)sin(x)

Gradient of {(x^2)y + (y^3)sin(x)} = (2xy + (y^3)cos(x), x^2 + 3(y^2)sin(x))

Q7

In [13]:


dict = {
    2022: {
        'Branch 1': {
            1: {
               'Roll Number': 1,
                'Name': 'N',
                'Marks': {
                    'Maths': 100,
                    'English': 70
                }
            }
        },
        'Branch 2': {}
    } ,
    2023:{
        'Branch 1': {},
        'Branch 2': {}
    },
    2024:{
        'Branch 1': {},
        'Branch 2': {}
    },
    2025:{
        'Branch 1': {},
        'Branch 2': {}
    }
}
dict

{2022: {'Branch 1': {1: {'Roll Number': 1,
    'Name': 'N',
    'Marks': {'Maths': 100, 'English': 70}}},
  'Branch 2': {}},
 2023: {'Branch 1': {}, 'Branch 2': {}},
 2024: {'Branch 1': {}, 'Branch 2': {}},
 2025: {'Branch 1': {}, 'Branch 2': {}}}

Q8

In [14]:


class Student:
    def __init__(self, roll_number, name):
        self.roll_number = roll_number
        self.name = name
        self.marks = {}

    def set_mark(self, subject, mark):
        self.marks[subject] = mark


class Branch:
    def __init__(self, name):
        self.name = name
        self.students = []

    def enroll_student(self, student):
        self.students.append(student)


class Year:
    def __init__(self, year):
        self.year = year
        self.branches = []

    def add_branch(self, branch):
        self.branches.append(branch)


year_2022 = Year(2022)

branch_1_2022 = Branch("Branch 1")
student_1_2022 = Student(1, "N")
student_1_2022.set_mark("Maths", 100)
student_1_2022.set_mark("English", 70)
branch_1_2022.enroll_student(student_1_2022)

branch_2_2022 = Branch("Branch 2")

year_2022.add_branch(branch_1_2022)
year_2022.add_branch(branch_2_2022)

year_2023 = Year(2023)
branch_1_2023 = Branch("Branch 1")
branch_2_2023 = Branch("Branch 2")
year_2023.add_branch(branch_1_2023)
year_2023.add_branch(branch_2_2023)

year_2024 = Year(2024)
branch_1_2024 = Branch("Branch 1")
branch_2_2024 = Branch("Branch 2")
year_2024.add_branch(branch_1_2024)
year_2024.add_branch(branch_2_2024)

year_2025 = Year(2025)
branch_1_2025 = Branch("Branch 1")
branch_2_2025 = Branch("Branch 2")
year_2025.add_branch(branch_1_2025)
year_2025.add_branch(branch_2_2025)

database = [year_2022, year_2023, year_2024, year_2025]

for year in database:
    print(year.year)
    for branch in year.branches:
        print(f"    {branch.name}")
        for student in branch.students:
            print(f"        Roll Number: {student.roll_number}, Name: {student.name}, Marks: {student.marks}")

2022
    Branch 1
        Roll Number: 1, Name: N, Marks: {'Maths': 100, 'English': 70}
    Branch 2
2023
    Branch 1
    Branch 2
2024
    Branch 1
    Branch 2
2025
    Branch 1
    Branch 2


Q12

In [15]:

import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

vector = np.array([10, 20, 30])

result = matrix + vector

print("Matrix:")
print(matrix)
print("\nVector:")
print(vector)
print("\nResult of broadcasting:")
print(result)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector:
[10 20 30]

Result of broadcasting:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


Q13

In [16]:

import numpy as np

def compute_argmin(arr):
    min_index = 0
    for i in range(1, len(arr)):
        if arr[i] < arr[min_index]:
            min_index = i
    return min_index

arr = np.array([5, 2, 9, 1, 5, 6])
result = compute_argmin(arr)
print("Computed index:", result)
print("Verification with np.argmin:", np.argmin(arr))



Computed index: 3
Verification with np.argmin: 3
